// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Services
	{
		/// <summary>Contains a service description. (Unicode)</summary>
		/// <remarks>
		/// <para>A description of <b>NULL</b> indicates no service description exists. The service description is NULL when the service is created. The description is simply a comment that explains the purpose of the service. For example, for the DHCP service, you could use the description "Provides internet addresses for computer on your network." You can set the description using the <a href="https://docs.microsoft.com/windows/desktop/api/winsvc/nf-winsvc-changeserviceconfig2a">ChangeServiceConfig2</a> function. You can retrieve the description using the <a href="https://docs.microsoft.com/windows/desktop/api/winsvc/nf-winsvc-queryserviceconfig2a">QueryServiceConfig2</a> function. The description is also displayed by the Services snap-in.</para>
		/// <para><see href="https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_descriptionw#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.106+a37a0b4b70")]
		internal partial struct SERVICE_DESCRIPTIONW
		{
			/// <summary>
			/// <para>The description of the service. If this member is <b>NULL</b>, the description remains unchanged. If this value is an empty string (""), the current description is deleted.</para>
			/// <para>The service description must not exceed the size of a registry value of type <b>REG_SZ</b>. This member can specify a localized string using the following format: @[<i>path</i>\]<i>dllname</i>,-<i>strID</i> The string with identifier <i>strID</i> is loaded from <i>dllname</i>; the <i>path</i> is optional. For more information, see <a href="https://docs.microsoft.com/windows/desktop/api/winreg/nf-winreg-regloadmuistringa">RegLoadMUIString</a>. <b>Windows Server 2003 and Windows XP:  </b>Localized strings are not supported until Windows Vista.</para>
			/// <para><see href="https://learn.microsoft.com/windows/win32/api/winsvc/ns-winsvc-service_descriptionw#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Foundation.PWSTR lpDescription;
		}
	}
}
