// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Services
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.106+a37a0b4b70")]
		internal enum SERVICE_CONFIG : uint
		{
			SERVICE_CONFIG_DELAYED_AUTO_START_INFO = 3U,
			SERVICE_CONFIG_DESCRIPTION = 1U,
			SERVICE_CONFIG_FAILURE_ACTIONS = 2U,
			SERVICE_CONFIG_FAILURE_ACTIONS_FLAG = 4U,
			SERVICE_CONFIG_PREFERRED_NODE = 9U,
			SERVICE_CONFIG_PRESHUTDOWN_INFO = 7U,
			SERVICE_CONFIG_REQUIRED_PRIVILEGES_INFO = 6U,
			SERVICE_CONFIG_SERVICE_SID_INFO = 5U,
			SERVICE_CONFIG_TRIGGER_INFO = 8U,
			SERVICE_CONFIG_LAUNCH_PROTECTED = 12U,
		}
	}
}
