// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
    namespace System.Services
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.106+a37a0b4b70")]
        internal enum SERVICE_START_TYPE : uint
        {
            SERVICE_AUTO_START = 2U,
            SERVICE_BOOT_START = 0U,
            SERVICE_DEMAND_START = 3U,
            SERVICE_DISABLED = 4U,
            SERVICE_SYSTEM_START = 1U,
            SERVICE_NO_CHANGE = 4294967295U,
        }
    }
}
